# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jake Hoertt
tagline:          Tools for information literacy
description:      "INLS 161"
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/karloespiritu/blackdoc
